"""
run_pipeline.py
---------------
Top-level orchestration script for the Indian SIP churn feature pipeline.

Two pipeline paths are executed in sequence:

A. AMFI Fund Pipeline (Stages 1–3)
   Uses the Kaggle AMFI mutual fund snapshot + derived monthly panel.
   Output: data/features/features_amfi.csv

B. Investor Pipeline (Stages 0, 4–6)
   Stage 0 simulates realistic Indian SIP investor data (idempotent).
   Stages 4–6 build the investor × month panel and engineer rich features.
   Output: data/features/features.csv  ← primary ML-ready dataset

Usage
-----
    python run_pipeline.py

All Outputs
-----------
data/raw/nifty50_monthly.csv           ← generated by Stage 0
data/raw/fund_nav_monthly.csv          ← generated by Stage 0
data/raw/sip_investors.csv             ← generated by Stage 0
data/processed/funds_clean.csv
data/processed/monthly_clean.csv
data/processed/merged_panel.csv
data/processed/merged_investor_panel.csv
data/features/features_amfi.csv        ← AMFI pipeline output
data/features/features.csv             ← Investor pipeline output (primary)
"""

import sys
from pathlib import Path

# ── Project root — resolves correctly from any working directory ──────────────
PROJECT_ROOT = Path(__file__).resolve().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.ingestion.simulate_investors import run_simulation
from src.ingestion.data_loader import load_all, load_investor_data_all
from src.ingestion.data_cleaning import run_cleaning
from src.ingestion.investor_cleaning import run_investor_cleaning
from src.features.feature_engineering import (
    run_feature_engineering,
    run_feature_engineering_investor,
)
from src.utils.logger import get_logger

log = get_logger(__name__)

# Absolute output paths — consistent regardless of working directory
AMFI_FEATURES_FILE     = PROJECT_ROOT / "data" / "features" / "features_amfi.csv"
INVESTOR_FEATURES_FILE = PROJECT_ROOT / "data" / "features" / "features.csv"


def main() -> None:
    """Execute both SIP churn feature pipelines end-to-end."""
    log.info("=" * 60)
    log.info("Indian SIP Churn — Full Feature Pipeline")
    log.info("=" * 60)

    # ── Stage 0: Simulate investor datasets (idempotent) ──────────────────────
    log.info("STAGE 0 / 6  Simulate investor datasets")
    run_simulation()   # skipped if files already exist

    # ══════════════════════════════════════════════════════════════════════════
    # PIPELINE A — AMFI fund-level pipeline (Stages 1–3)
    # ══════════════════════════════════════════════════════════════════════════
    log.info("-" * 60)
    log.info("PIPELINE A  AMFI fund panel")
    log.info("-" * 60)

    # ── Stage 1: Ingestion ────────────────────────────────────────────────────
    log.info("STAGE 1 / 6  Ingestion (AMFI)")
    try:
        df_funds, df_monthly = load_all()
    except FileNotFoundError as exc:
        log.error("AMFI raw data not found: %s", exc)
        log.error(
            "Run `python data/prepare_dataset.py` to download the AMFI "
            "fund files, then retry."
        )
        sys.exit(1)

    # ── Stage 2: Cleaning ─────────────────────────────────────────────────────
    log.info("STAGE 2 / 6  Cleaning (AMFI)")
    _, _, df_merged = run_cleaning(df_funds, df_monthly)

    # ── Stage 3: Feature Engineering ─────────────────────────────────────────
    log.info("STAGE 3 / 6  Feature Engineering (AMFI)")
    df_amfi = run_feature_engineering(df_merged, out_path=AMFI_FEATURES_FILE)

    # ══════════════════════════════════════════════════════════════════════════
    # PIPELINE B — Investor-level pipeline (Stages 4–6)
    # ══════════════════════════════════════════════════════════════════════════
    log.info("-" * 60)
    log.info("PIPELINE B  Investor × month panel")
    log.info("-" * 60)

    # ── Stage 4: Ingestion (investor datasets) ────────────────────────────────
    log.info("STAGE 4 / 6  Ingestion (Investor)")
    try:
        df_nifty, df_nav, df_investors = load_investor_data_all()
    except FileNotFoundError as exc:
        log.error("Investor raw data not found: %s", exc)
        log.error(
            "Run `python src/ingestion/simulate_investors.py` to generate "
            "the investor dataset files, then retry."
        )
        sys.exit(1)

    # ── Stage 5: Cleaning + panel construction ────────────────────────────────
    log.info("STAGE 5 / 6  Cleaning (Investor)")
    df_panel = run_investor_cleaning(df_investors, df_nav, df_nifty)

    # ── Stage 6: Feature Engineering ─────────────────────────────────────────
    log.info("STAGE 6 / 6  Feature Engineering (Investor)")
    df_features = run_feature_engineering_investor(
        df_panel, out_path=INVESTOR_FEATURES_FILE
    )

    # ── Summary ───────────────────────────────────────────────────────────────
    log.info("=" * 60)
    log.info("Pipeline complete.")
    log.info("  AMFI features     : %s  shape=%s",
             AMFI_FEATURES_FILE, df_amfi.shape)
    log.info("  Investor features : %s  shape=%s",
             INVESTOR_FEATURES_FILE, df_features.shape)
    log.info("  Investor churn rate : %.2f%%",
             df_features["churn"].mean() * 100)
    log.info("=" * 60)


if __name__ == "__main__":
    main()

