"""
src/ingestion/data_loader.py
-----------------------------
Stage 1 – Raw data ingestion for the Indian SIP churn pipeline.

Two real-world datasets are supported out of the box:

1. **india_mf_funds.csv**  (fund-level snapshot)
   Source: Kaggle "Mutual Funds India – Detailed" (AMFI data)
   814 Indian MF schemes with expense ratio, returns, risk metrics.

2. **sip_india_monthly.csv**  (fund × month panel)
   Derived from the fund-level data: 814 funds × 120 months → 87 912
   fund-month rows carrying time-varying performance indicators.

Three additional simulated Indian financial datasets (generated by
``src/ingestion/simulate_investors.py``) are also supported:

3. **nifty50_monthly.csv**    – monthly NIFTY 50 price / return data
4. **fund_nav_monthly.csv**   – monthly NAV for 20 Indian MF schemes
5. **sip_investors.csv**      – 5 000 synthetic SIP investor records

Responsibilities of this module
--------------------------------
- Locate raw CSV files under ``data/raw/``.
- Standardise column names (lowercase, underscored).
- Validate that mandatory columns are present.
- Return clean DataFrames ready for the cleaning stage.

Running this script
-------------------
Can be invoked directly from any working directory to verify datasets::

    python src/ingestion/data_loader.py
"""

import sys
from pathlib import Path

# Allow running this file directly: python src/ingestion/data_loader.py
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import pandas as pd

from src.utils.io_helpers import read_csv
from src.utils.logger import get_logger

log = get_logger(__name__)

# ── Absolute paths (work from any working directory) ──────────────────────────
_RAW_DIR       = _PROJECT_ROOT / "data" / "raw"
RAW_DIR        = _RAW_DIR
FUNDS_FILE     = _RAW_DIR / "india_mf_funds.csv"
MONTHLY_FILE   = _RAW_DIR / "sip_india_monthly.csv"
NIFTY_FILE     = _RAW_DIR / "nifty50_monthly.csv"
FUND_NAV_FILE  = _RAW_DIR / "fund_nav_monthly.csv"
INVESTORS_FILE = _RAW_DIR / "sip_investors.csv"

# Mandatory columns for each dataset
FUNDS_REQUIRED_COLS = {
    "fund_id", "scheme_name", "amc_name", "category", "expense_ratio",
    "risk_level", "rating", "fund_size_cr", "fund_age_yr",
    "returns_1yr", "returns_3yr", "returns_5yr",
}
MONTHLY_REQUIRED_COLS = {
    "fund_id", "month", "monthly_return", "roll_3m_return",
    "roll_6m_return", "roll_12m_return", "drawdown",
    "rel_perf_vs_cat", "churn",
}
NIFTY_REQUIRED_COLS = {
    "date", "nifty_close", "nifty_monthly_return",
}
FUND_NAV_REQUIRED_COLS = {
    "date", "fund_name", "nav", "monthly_return",
}
INVESTORS_REQUIRED_COLS = {
    "investor_id", "fund_name", "monthly_investment",
    "sip_start_date", "missed_payments", "status",
}


# ── Helpers ───────────────────────────────────────────────────────────────────

def _standardise_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Lowercase all column names and replace spaces / hyphens with underscores.

    Parameters
    ----------
    df:
        Input DataFrame.

    Returns
    -------
    pd.DataFrame
        DataFrame with cleaned column names.
    """
    df = df.copy()
    df.columns = (
        df.columns.str.strip()
                  .str.lower()
                  .str.replace(r"[\s\-]+", "_", regex=True)
                  .str.replace(r"[^\w]", "", regex=True)
    )
    return df


def _validate_columns(df: pd.DataFrame, required: set, label: str) -> None:
    """Assert that all required columns are present.

    Parameters
    ----------
    df:
        DataFrame to validate.
    required:
        Set of column names that must exist.
    label:
        Human-readable name for the dataset (used in error messages).

    Raises
    ------
    ValueError
        If one or more required columns are absent.
    """
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"[{label}] Missing required columns: {sorted(missing)}"
        )
    log.info("[%s] Schema validation passed (%d columns present)", label, len(df.columns))


# ── Public loaders ────────────────────────────────────────────────────────────

def load_funds(path: str | Path = FUNDS_FILE) -> pd.DataFrame:
    """Load and lightly standardise the fund-level snapshot.

    Parameters
    ----------
    path:
        Path to ``india_mf_funds.csv``.

    Returns
    -------
    pd.DataFrame
        Standardised fund-level DataFrame.
    """
    log.info("Loading fund-level data from %s", path)
    df = read_csv(path)
    df = _standardise_columns(df)
    _validate_columns(df, FUNDS_REQUIRED_COLS, "india_mf_funds")
    log.info("Fund-level data loaded: %d funds", len(df))
    return df


def load_monthly(path: str | Path = MONTHLY_FILE) -> pd.DataFrame:
    """Load and lightly standardise the fund × month panel data.

    Parameters
    ----------
    path:
        Path to ``sip_india_monthly.csv``.

    Returns
    -------
    pd.DataFrame
        Standardised monthly panel DataFrame.
    """
    log.info("Loading monthly panel data from %s", path)
    df = read_csv(path)
    df = _standardise_columns(df)
    _validate_columns(df, MONTHLY_REQUIRED_COLS, "sip_india_monthly")
    log.info("Monthly panel loaded: %d fund-month rows", len(df))
    return df


def load_all(
    funds_path: str | Path = FUNDS_FILE,
    monthly_path: str | Path = MONTHLY_FILE,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Convenience wrapper that loads both AMFI datasets at once.

    Parameters
    ----------
    funds_path:
        Path to the fund-level CSV.
    monthly_path:
        Path to the monthly panel CSV.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame]
        ``(df_funds, df_monthly)``
    """
    df_funds   = load_funds(funds_path)
    df_monthly = load_monthly(monthly_path)
    return df_funds, df_monthly


# ── Loaders for simulated investor datasets ───────────────────────────────────

def load_nifty(path: str | Path = NIFTY_FILE) -> pd.DataFrame:
    """Load NIFTY 50 monthly data produced by ``simulate_investors.py``.

    Parameters
    ----------
    path:
        Path to ``nifty50_monthly.csv``.

    Returns
    -------
    pd.DataFrame
        NIFTY 50 monthly DataFrame with ``date`` parsed as datetime.
    """
    log.info("Loading NIFTY 50 monthly data from %s", path)
    df = read_csv(path, parse_dates=["date"])
    df = _standardise_columns(df)
    _validate_columns(df, NIFTY_REQUIRED_COLS, "nifty50_monthly")
    df["date"] = pd.to_datetime(df["date"])
    log.info("NIFTY 50 loaded: %d months", len(df))
    return df


def load_fund_nav(path: str | Path = FUND_NAV_FILE) -> pd.DataFrame:
    """Load monthly fund NAV data produced by ``simulate_investors.py``.

    Parameters
    ----------
    path:
        Path to ``fund_nav_monthly.csv``.

    Returns
    -------
    pd.DataFrame
        Fund NAV monthly panel with ``date`` parsed as datetime.
    """
    log.info("Loading fund NAV monthly data from %s", path)
    df = read_csv(path, parse_dates=["date"])
    df = _standardise_columns(df)
    _validate_columns(df, FUND_NAV_REQUIRED_COLS, "fund_nav_monthly")
    df["date"] = pd.to_datetime(df["date"])
    log.info("Fund NAV loaded: %d rows (%d unique funds)",
             len(df), df["fund_name"].nunique())
    return df


def load_investors(path: str | Path = INVESTORS_FILE) -> pd.DataFrame:
    """Load the simulated SIP investor dataset.

    Parameters
    ----------
    path:
        Path to ``sip_investors.csv``.

    Returns
    -------
    pd.DataFrame
        Investor DataFrame with ``sip_start_date`` and ``sip_end_date``
        parsed as datetime (NaT for active investors with no end date).
    """
    log.info("Loading SIP investor data from %s", path)
    df = read_csv(path)
    df = _standardise_columns(df)
    _validate_columns(df, INVESTORS_REQUIRED_COLS, "sip_investors")

    # Parse dates — sip_end_date may be empty string for active investors
    df["sip_start_date"] = pd.to_datetime(df["sip_start_date"], errors="coerce")
    df["sip_end_date"]   = pd.to_datetime(
        df["sip_end_date"].replace("", pd.NA), errors="coerce"
    )
    log.info(
        "Investors loaded: %d total  active=%d  stopped=%d",
        len(df),
        (df["status"] == "active").sum(),
        (df["status"] == "stopped").sum(),
    )
    return df


def load_investor_data_all(
    nifty_path:     str | Path = NIFTY_FILE,
    nav_path:       str | Path = FUND_NAV_FILE,
    investors_path: str | Path = INVESTORS_FILE,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Convenience wrapper: load all three investor-pipeline datasets.

    Parameters
    ----------
    nifty_path:
        Path to ``nifty50_monthly.csv``.
    nav_path:
        Path to ``fund_nav_monthly.csv``.
    investors_path:
        Path to ``sip_investors.csv``.

    Returns
    -------
    tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]
        ``(df_nifty, df_nav, df_investors)``
    """
    df_nifty     = load_nifty(nifty_path)
    df_nav       = load_fund_nav(nav_path)
    df_investors = load_investors(investors_path)
    return df_nifty, df_nav, df_investors


def main() -> None:
    """Entry-point: load all five datasets and print a summary.

    Useful for quickly verifying that all raw CSV files are present and
    have the expected structure.  Run from any directory::

        python src/ingestion/data_loader.py
    """
    errors: list[str] = []

    def _try_load(name: str, loader, *args):
        try:
            return loader(*args)
        except FileNotFoundError as exc:
            log.error("%s: %s", name, exc)
            errors.append(name)
            return None

    df_funds   = _try_load("india_mf_funds",     load_funds)
    df_monthly = _try_load("sip_india_monthly",  load_monthly)
    df_nifty   = _try_load("nifty50_monthly",    load_nifty)
    df_nav     = _try_load("fund_nav_monthly",   load_fund_nav)
    df_investors = _try_load("sip_investors",    load_investors)

    print("\n── Dataset summary ──────────────────────────────────────")
    for label, df in [
        ("india_mf_funds",    df_funds),
        ("sip_india_monthly", df_monthly),
        ("nifty50_monthly",   df_nifty),
        ("fund_nav_monthly",  df_nav),
        ("sip_investors",     df_investors),
    ]:
        if df is not None:
            print(f"  {label:<24} shape={df.shape}")
        else:
            print(f"  {label:<24} MISSING — run prepare_dataset.py or simulate_investors.py")

    if errors:
        print(
            f"\n{len(errors)} file(s) missing.  "
            "Run `python data/prepare_dataset.py` (AMFI data) or "
            "`python src/ingestion/simulate_investors.py` (investor data) "
            "to generate them.",
            file=sys.stderr,
        )
        sys.exit(1)


if __name__ == "__main__":
    main()
